---
- hosts: all

  tasks:
    - name: Incluir el rol 2do_parcial
      include_role:
        name: 2do_parcial
    
    - name: "Mensaje después de ejecutar el rol"
      debug:
        msg: "Tareas del rol ejecutadas correctamente"
